import os 

SQLALCHEMY_DATABASE_URI = "sqlite:///db.sqlite3"
SQLALCHEMY_TRACK_MODIFICATIONS = False

HCAPTCHA_ENABLED = False
HCAPTCHA_SITE_KEY = ''
HCAPTCHA_SECRET_KEY = ''

LIMIT_SHORTENS = False
LIMIT_COUNT = 0

SERVER_NAME="127.0.0.1:5001"
